<div class="jumbotron">
    <h1>Willkommen beim <span class="zf-green">Zend Framework</span></h1>

    <p>
        Glückwunsch! Du hast erfolgreich die
        <a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">MEIKO Skeleton Application</a> installiert.
        Du verwendest aktuelle die Verison <?= \Application\Module::VERSION ?> des Zend Frameworks.
        Dieses Vorlage kann zum einfachen Start in die Entwicklung einer Anwendung verwendet werden.
    </p>

    <p><a class="btn btn-success btn-lg" href="https://github.com/zendframework/zendframework" target="_blank"><?= $this->translate('Fork Zend Framework on GitHub') ?> &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Systemprüfung</h3>
            </div>
            <div class="panel-body">
                <p>
                    Prüfe, ob das System den Anforderungen von MEIKO entspricht.
                </p>

                <p><a class="btn btn-success pull-right" href="/administration/check" target="_blank">Systemprüfung &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">JSON</h3>
            </div>
            <div class="panel-body">
                <p>
                    Schaue dir den Test-Controller an, der JSON zurückliefert.
                </p>

                <p><a class="btn btn-success pull-right" href="/api/test" target="_blank">JSON &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('Help and Support'); ?></h3>
            </div>
            <div class="panel-body">
                <p>
                    Das Internet hilft dir... <br>du musst nur richtig suchen.
                </p>

                <p><a class="btn btn-success pull-right" href="http://www.google.de" target="_blank">Google &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
